import type { ArmorModel } from '@/types/ArmorModel.ts'

export const armorList: ArmorModel[] = [
  {
    id: 'a1',
    name: "Кожаный доспех",
    type: "лёгкий",
    ac: 11,
    stealthDisadvantage: false,
    weight: 10,
    cost: 1000,
  },
  {
    id: 'a2',
    name: "Проклёпанная кожа",
    type: "лёгкий",
    ac: 12,
    stealthDisadvantage: false,
    weight: 13,
    cost: 4500,
  },
  {
    id: 'a3',
    name: "Кольчужная рубаха",
    type: "средний",
    ac: 13,
    stealthDisadvantage: false,
    weight: 20,
    cost: 5000,
  },
  {
    id: 'a4',
    name: "Чешуйчатая броня",
    type: "средний",
    ac: 14,
    stealthDisadvantage: true,
    weight: 45,
    cost: 5000,
  },
  {
    id: 'a5',
    name: "Кираса",
    type: "средний",
    ac: 14,
    stealthDisadvantage: false,
    weight: 20,
    cost: 40000,
  },
  {
    id: 'a6',
    name: "Полулаты",
    type: "средний",
    ac: 15,
    stealthDisadvantage: true,
    weight: 40,
    cost: 75000,
  },
  {
    id: 'a7',
    name: "Кольчуга",
    type: "тяжёлый",
    ac: 16,
    strengthRequirement: 13,
    stealthDisadvantage: true,
    weight: 55,
    cost: 7500,
  },
  {
    id: 'a8',
    name: "Наборный доспех",
    type: "тяжёлый",
    ac: 17,
    strengthRequirement: 15,
    stealthDisadvantage: true,
    weight: 60,
    cost: 20000,
  },
  {
    id: 'a9',
    name: "Латы",
    type: "тяжёлый",
    ac: 18,
    strengthRequirement: 15,
    stealthDisadvantage: true,
    weight: 65,
    cost: 150000,
  },
  {
    id: 'a10',
    name: "Щит",
    type: "щит",
    ac: 2,
    stealthDisadvantage: false,
    weight: 6,
    cost: 1000,
  },
  {
    id: 'a11',
    name: "Стёганный доспех",
    type: "лёгкий",
    ac: 11,
    stealthDisadvantage: true,
    weight: 8,
    cost: 500,
  },
  {
    id: 'a12',
    name: "Шкурный доспех",
    type: "средний",
    ac: 12,
    stealthDisadvantage: true,
    weight: 12,
    cost: 1000,
  },
  {
    id: 'a13',
    name: "Кольчатый доспех",
    type: "тяжёлый",
    ac: 14,
    stealthDisadvantage: true,
    weight: 40,
    cost: 3000,
  }
]
