import type {WeaponModel } from '@/types/WeaponModel.ts'

export const weaponList: WeaponModel[] = [
  {
    id: 'w1',
    name: "Дубинка",
    type: "ближний",
    damage: "1d4",
    damageType: "дробящий",
    properties: ["лёгкое"],
    weight: 2,
    cost: 10,
    proficient: true,
  },
  {
    id: 'w2',
    name: "Кинжал",
    type: "ближний",
    damage: "1d4",
    damageType: "колющий",
    properties: ["фехтовальное ", "лёгкое", "метательное (дистанция 20/60)"],
    weight: 1,
    cost: 200,
    proficient: true,
  },
  {
    id: 'w3',
    name: "Палица",
    type: "ближний",
    damage: "1d8",
    damageType: "дробящий",
    properties: ["двуручное"],
    weight: 10,
    cost: 20,
    proficient: true,
  },
  {
    id: 'w4',
    name: "Ручной топор",
    type: "ближний",
    damage: "1d6",
    damageType: "рубящий",
    properties: ["лёгкое", "метательное (дистанция 20/60)"],
    weight: 2,
    cost: 500,
    proficient: true,
  },
  {
    id: 'w5',
    name: "Алебарда",
    type: "ближний",
    damage: "1d10",
    damageType: "рубящий",
    properties: ["двуручное","досягаемость","тяжелое"],
    weight: 2,
    cost: 2000,
    proficient: true,
  },
  {
    id: 'w6',
    name: "Лёгкий молот",
    type: "ближний",
    damage: "1d4",
    damageType: "дробящий",
    properties: ["лёгкое", "метательное (дистанция 20/60)"],
    weight: 2,
    cost: 200,
    proficient: true,
  },
  {
    id: 'w7',
    name: "Булава",
    type: "ближний",
    damage: "1d6",
    damageType: "дробящий",
    properties: [],
    weight: 4,
    cost: 500,
    proficient: true,
  },
  {
    id: 'w8',
    name: "Боевой посох",
    type: "ближний",
    damage: "1d6",
    damageType: "дробящий",
    properties: ["универсальное (1d8)"],
    weight: 4,
    cost: 20,
    proficient: true,
  },
  {
    id: 'w9',
    name: "Серп",
    type: "ближний",
    damage: "1d4",
    damageType: "рубящий",
    properties: ["лёгкое"],
    weight: 2,
    cost: 100,
    proficient: true,
  },
  {
    id: 'w10',
    name: "Копьё",
    type: "ближний",
    damage: "1d6",
    damageType: "колющий",
    properties: ["метательное (дистанция 20/60)", "универсальное (1d8)"],
    range: [20, 60],
    weight: 3,
    cost: 100,
    proficient: true,
  },
  {
    id: 'w11',
    name: "Лёгкий арбалет",
    type: "дальний",
    damage: "1d8",
    damageType: "колющий",
    properties: ["боеприпасы (дистанция 80/320)", "перезарядка", "двуручное"],
    weight: 5,
    cost: 2500,
    proficient: true,
  },
  {
    id: 'w12',
    name: "Дротик",
    type: "дальний",
    damage: "1d4",
    damageType: "колющий",
    properties: ["фехтовальное", "метательное (дистанция 20/60)"],
    weight: 0.25,
    cost: 5,
    proficient: true,
  },
  {
    id: 'w13',
    name: "Тяжёлый арбалет",
    type: "дальний",
    damage: "1d10",
    damageType: "колющий",
    properties: ["боеприпасы (дистанция 100/400)", "перезарядка", "двуручное", "тяжёлое"],
    weight: 18,
    cost: 5000,
    proficient: true,
  },
  {
    id: 'w14',
    name: "Короткий лук",
    type: "дальний",
    damage: "1d6",
    damageType: "колющий",
    properties: ["боеприпасы (дистанция 80/320)", "двуручное"],
    weight: 2,
    cost: 2500,
    proficient: true,
  },
  {
    id: 'w15',
    name: "Праща",
    type: "дальний",
    damage: "1d4",
    damageType: "дробящий",
    properties: ["боеприпасы (дистанция 30/120)"],
    weight: 0,
    cost: 10,
    proficient: true,
  },
  {
    id: 'w16',
    name: "Боевой топор",
    type: "ближний",
    damage: "1d8",
    damageType: "рубящий",
    properties: ["универсальное (1d10)"],
    weight: 4,
    cost: 1000,
    proficient: true,
  },
  {
    id: 'w17',
    name: "Боевой молот",
    type: "ближний",
    damage: "1d8",
    damageType: "дробящий",
    properties: ["универсальное (1d10)"],
    weight: 2,
    cost: 1500,
    proficient: true,
  },
  {
    id: 'w18',
    name: "Глефа",
    type: "ближний",
    damage: "1d10",
    damageType: "рубящий",
    properties: ["досягаемость", "двуручное", "тяжёлое"],
    weight: 6,
    cost: 2000,
    proficient: true,
  },
  {
    id: 'w19',
    name: "Двуручный меч",
    type: "ближний",
    damage: "2d6",
    damageType: "рубящий",
    properties: ["двуручное", "тяжёлое"],
    weight: 6,
    cost: 5000,
    proficient: true,
  },
  {
    id: 'w20',
    name: "Длинный меч",
    type: "ближний",
    damage: "1d8",
    damageType: "рубящий",
    properties: ["универсальное (1d10)"],
    weight: 3,
    cost: 1500,
    proficient: true,
  },
  {
    id: 'w22',
    name: "Длинное копьё",
    type: "ближний",
    damage: "1d12",
    damageType: "колющий",
    properties: ["досягаемость", "особое"],
    weight: 6,
    cost: 1000,
    proficient: true,
  },
  {
    id: 'w23',
    name: "Рапира",
    type: "ближний",
    damage: "1d8",
    damageType: "колющий",
    properties: ["фехтовальное"],
    weight: 2,
    cost: 2500,
    proficient: true,
  },
  {
    id: 'w24',
    name: "Скимитар",
    type: "ближний",
    damage: "1d6",
    damageType: "рубящий",
    properties: ["фехтовальное", "лёгкое"],
    weight: 3,
    cost: 2500,
    proficient: true,
  },
  {
    id: 'w25',
    name: "Трезубец",
    type: "ближний",
    damage: "1d6",
    damageType: "колющий",
    properties: ["метательное (дистанция 20/60)", "универсальное (1d8)"],
    weight: 4,
    cost: 500,
    proficient: true,
  },
  {
    id: 'w26',
    name: "Цеп",
    type: "ближний",
    damage: "1d8",
    damageType: "дробящий",
    properties: [],
    weight: 2,
    cost: 1000,
    proficient: true,
  },
  {
    id: 'w27',
    name: "Длинный лук",
    type: "дальний",
    damage: "1d8",
    damageType: "колющий",
    properties: ["боеприпасы (дистанция 150/600)", "двуручное", "тяжёлое"],
    weight: 2,
    cost: 5000,
    proficient: true,
  },
  {
    id: 'w28',
    name: "Ручной арбалет",
    type: "дальний",
    damage: "1d6",
    damageType: "колющий",
    properties: ["боеприпасы (дистанция 30/120)", "перезарядка", "лёгкое"],
    weight: 3,
    cost: 7500,
    proficient: true,
  },
  {
    id: 'w30',
    name: "Сеть",
    type: "дальний",
    damage: "—",
    damageType: "дробящий",
    properties: ["особое", "метательное (дистанция 5/15)"],
    weight: 3,
    cost: 100,
    proficient: true,
  },
  {
    id: 'w31',
    name: "Метательное копьё",
    type: "дальний",
    damage: "1d6",
    damageType: "колющий",
    properties: ["метательное (дистанция 30/120)"],
    weight: 2,
    cost: 50,
    proficient: true,
  },
  {
    id: 'w32',
    name: "Боевая кирка",
    type: "ближний",
    damage: "1d8",
    damageType: "колющий",
    properties: [],
    weight: 2,
    cost: 500,
    proficient: true,
  },
  {
    id: 'w33',
    name: "Кнут",
    type: "ближний",
    damage: "1d4",
    damageType: "рубящий",
    properties: ["досягаемость","фехтовальное"],
    weight: 3,
    cost: 200,
    proficient: true,
  },
  {
    id: 'w34',
    name: "Короткий меч",
    type: "ближний",
    damage: "1d6",
    damageType: "колющий",
    properties: ["легкое","фехтовальное"],
    weight: 2,
    cost: 1000,
    proficient: true,
  },
  {
    id: 'w35',
    name: "Молот",
    type: "ближний",
    damage: "2d6",
    damageType: "дробящий",
    properties: ["двуручное","тяжелое"],
    weight: 10,
    cost: 1000,
    proficient: true,
  },
  {
    id: 'w36',
    name: "Моргенштерн",
    type: "ближний",
    damage: "1d8",
    damageType: "колющий",
    properties: [],
    weight: 4,
    cost: 1500,
    proficient: true,
  },
  {
    id: 'w37',
    name: "Пика",
    type: "ближний",
    damage: "1d10",
    damageType: "колющий",
    properties: ["двуручное","досягаемость","тяжелое"],
    weight: 18,
    cost: 500,
    proficient: true,
  },
  {
    id: 'w38',
    name: "Секира",
    type: "ближний",
    damage: "1d12",
    damageType: "рубящий",
    properties: ["двуручное","тяжелое"],
    weight: 7,
    cost: 3000,
    proficient: true,
  },
  {
    id: 'w39',
    name: "Духовая трубка",
    type: "дальний",
    damage: "1",
    damageType: "колющий",
    properties: ["боеприпасы (дистанция 25/100)","перезарядка"],
    weight: 1,
    cost: 1000,
    proficient: true,
  }

]
